### ISSUE TITLE
Awesome stuff - I've been re-inventing your wheel!

### ISSUE THREAD

**Issue by cohix** [wapc/wapc-go#3]
Hello! I came across this project after watching a talk from the Wasm Summit.

For context, I'm the lead developer of the Product Discovery team at 1Password.

I've been working on the [Suborbital Development Platform](github.com/suborbital) for some time now, and one of its main goals is to create a viable server-side Wasm framework. 

It would appear that I have inadvertently re-created some of the work you're doing here! The `hivew` toolchain I've been building includes what I've been calling the "Runnable FFI API", and it appears to be doing a lot of similar things to waPC!

I'm curious - would there be interest in having a call some time to see how I could potentially stop re-inventing the wheel and perhaps migrate the Hive FFI API over to waPC? I would of course love to contribute to this project as well. I would hate to fragment any kind of standard in this young ecosystem.

Please let me know! My email is connor at suborbital dot dev

**Comment by pkedy** [comment]
Per our chat on Discord, you are happy with the solution you have now. And agreed, I look forward to when a more built in ABI/FFI solution exists in all languages. Cheers!
