### ISSUE TITLE
Expose wazero module functions

### ISSUE THREAD

**Issue by Arsen6331** [wapc/wapc-go#34]
Currently, the wazero engine takes over all the initialization for a module. It creates the runtime, compiles the module, creates the module config, etc. The issue is that I might want to customize something in that. For example, I want to provide my own stdout, stderr, stdin, and I want to set some env variables.

I propose that instead of creating the module within the library, you simply take a wazero runtime, as well as maybe a config struct containing all the required stuff for the exports, if needed, and export all the required functions, similar to wazero's own [wasi_snapshot_preview1](https://github.com/tetratelabs/wazero/blob/main/wasi_snapshot_preview1/wasi.go#L40) package. This will allow users to do whatever they need to for their modules using wazero's API for that purpose instead of having to alter them to fit wapc's code.

If you want to keep the current interface, you can simply add new functions that do what I described and let users choose if they want a more out-of-the-box experience or if they want to customize things. This issue entirely prevents me from using this library, as much as I want to, because I need to customize some things in order to run the modules I need to run.

Also, using `func(string)` for stdout is a horrible, horrible choice and will on its own discourage most Go developers from ever using this library. Stdout should always be an `io.Writer`, as that is how Go represents data streams such as stdout.

**Comment by codefromthecrypt** [comment]
this should be incremental progress towards your request. I'll look further into this post-merge! https://github.com/wapc/wapc-go/pull/35

**Comment by codefromthecrypt** [comment]
https://github.com/wapc/wapc-go/pull/36 should sort this

**Comment by Arsen6331** [comment]
That looks good. Thank you for doing it so quickly.
